export enum PersonType {
  PROTAGONIST = 'PROTAGONIST',
  ANTAGONIST = 'ANTAGONIST',
  SUPPORTING = 'SUPPORTING',
  SECONDARY = 'SECONDARY',
  ADVERSARY = 'ADVERSARY',
  MENTOR = 'MENTOR',
  COMIC = 'COMIC',
  SYMBOLIC = 'SYMBOLIC',
  EXTRA = 'EXTRA',
}
