export enum PersonType {
  PROTAGONIST = 'PROTAGONIST',
  ANTAGONIST = 'ANTAGONIST',
  SUPPORTING = 'SUPPORTING',
  SECONDARY = 'SECONDARY',
  ADVERSARY = 'ADVERSARY',
  MENTOR = 'MENTOR',
  COMIC = 'COMIC',
  SYMBOLIC = 'SYMBOLIC',
  EXTRA = 'EXTRA',
}

export enum AttributeType {
  APPEARENCE = 'APPEARENCE',
  DREAM = 'DREAM',
  OBJECTIVE = 'OBJECTIVE',
  PERSONALITY = 'PERSONALITY',
  TRAUMA = 'TRAUMA',
  VALUE = 'VALUE',
}
